In [1]:
#importing libraries 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import yfinance
from ta import add_all_ta_features
import yfinance
from prophet import Prophet
import os
from ta import add_all_ta_features
import pickle

from sklearn.decomposition import PCA

%matplotlib inline

/Users/vipin/opt/anaconda3/envs/my_own/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Importing plotly failed. Interactive plots will not work.

In [2]:

# Data Extraction
symbol = "TATAELXSI.NS"
#symbols = ["OLECTRA.NS","CONCOR.NS","ELGIEQUIP.NS","IOC.NS","BEL.NS","TATAELXSI.NS","^NSEI","HDFCBANK.NS","TATAMOTORS.NS","SBIN.NS","TCS.NS","TITAN.NS","SUNPHARMA.BO","TECHM.NS", "ASIANPAINT.NS","TATACONSUM.NS"]

#df = pd.read_csv("./stock_historical_data/{}.csv".format(symbol))
df = yfinance.download (tickers = "{}".format(symbol),start="2007-03-06",
                            interval = "1d", group_by = 'ticker', auto_adjust = True)



df = df[["Open", "High", "Low", "Close","Volume"]]
df["Returns"] = df["Close"].pct_change()
df["Range"] = df["High"] / df["Low"] - 1
df["Avg_Range"] = df["Range"].rolling(window=30).mean()
df.tail()

def exponential_moving_average(data, window):
    if len(data) < window:
        raise ValueError("Data length should be greater than or equal to the window size.")
    
    alpha = 2 / (window + 1)
    ema = [data[0]]

    for i in range(1, len(data)):
        ema_value = alpha * data[i] + (1 - alpha) * ema[-1]
        ema.append(ema_value)
    return ema

[*********************100%***********************]  1 of 1 completed

In [3]:
#moving av
df['MA5'] = df.Close.rolling(window=5).mean()
df['EMA5'] = exponential_moving_average(df.Close.values,5)

df['MA10'] = df.Close.rolling(window=50).mean()
df['EMA10'] = exponential_moving_average(df.Close.values,10)

df['MA20'] = df.Close.rolling(window=20).mean()
df['EMA20'] = exponential_moving_average(df.Close.values,20)

df['MA50'] = df.Close.rolling(window=50).mean()
df['EMA50'] = exponential_moving_average(df.Close.values,50)

df['MA100'] = df.Close.rolling(window=100).mean()
df['EMA100'] = exponential_moving_average(df.Close.values,100)

#df['MA200'] =  df.Close.rolling(window=200).mean()
df.dropna(inplace=True)

In [4]:
#prophet
pro_df = df.copy()
pro_df["Date"] = pd.to_datetime(pro_df.index)
#renaming variables
pro_df = pro_df.rename(columns = {'Close': 'y',
                     'Date': 'ds'})
pro_df.reset_index()

pro_df.tail(10)

,Open,High,Low,y,Volume,Returns,Range,Avg_Range,MA5,EMA5,MA10,EMA10,MA20,EMA20,MA50,EMA50,MA100,EMA100,ds
Date,,,,,,,,,,,,,,,,,,,
2023-07-24,96.763492,97.636102,96.472617,96.811966,19073238,0.005033,0.012060,0.018944,95.755132,95.892767,89.503319,95.062677,93.083955,93.499400,89.503319,89.595824,83.137580,85.231046,2023-07-24
2023-07-25,96.908924,97.199799,95.696956,95.987831,11983867,-0.008513,0.015704,0.018802,96.026613,95.924455,89.790313,95.230887,93.542079,93.736393,89.790313,89.846491,83.347493,85.444052,2023-07-25
2023-07-26,96.811966,97.151315,95.842392,96.569572,14912431,0.006061,0.013657,0.018748,96.288397,96.139494,90.034646,95.474284,94.038986,94.006220,90.034646,90.110141,83.568071,85.664359,2023-07-26
2023-07-27,97.345235,97.393709,95.115211,95.599998,16349608,-0.010040,0.023955,0.019003,96.259309,95.959662,90.248922,95.497141,94.487414,94.158008,90.248922,90.325430,83.786710,85.861105,2023-07-27
2023-07-28,96.199997,96.599998,94.250000,95.250000,27278447,-0.003661,0.024934,0.019438,96.043874,95.723108,90.486254,95.452207,94.823808,94.262008,90.486254,90.518550,83.993123,86.047023,2023-07-28
2023-07-31,96.000000,96.199997,93.000000,93.750000,25418124,-0.015748,0.034409,0.020114,95.431480,95.065405,90.692617,95.142715,94.893712,94.213245,90.692617,90.645274,84.175325,86.199558,2023-07-31
2023-08-01,93.800003,94.750000,93.300003,94.000000,16132927,0.002667,0.015541,0.020195,95.033914,94.710270,90.882650,94.934948,95.005202,94.192936,90.882650,90.776832,84.357118,86.354022,2023-08-01
2023-08-02,94.400002,94.650002,93.000000,93.849998,16780965,-0.001596,0.017742,0.020312,94.489999,94.423513,91.033808,94.737685,95.067986,94.160275,91.033808,90.897348,84.527230,86.502457,2023-08-02
2023-08-03,93.900002,94.199997,93.150002,93.500000,8703991,-0.003729,0.011272,0.020270,94.070000,94.115675,91.165362,94.512651,94.962986,94.097392,91.165362,90.999413,84.694328,86.641022,2023-08-03
2023-08-04,93.550003,93.900002,92.050003,92.300003,10743670,-0.012834,0.020098,0.020540,93.480000,93.510451,91.282611,94.110351,94.768900,93.926212,91.282611,91.050416,84.854273,86.753081,2023-08-04

In [5]:
m = Prophet(
            #holidays = holidays,
            #seasonality_mode = 'multiplicative',
           # seasonality_prior_scale = 20,
            #changepoint_prior_scale = 0.1,
           # holidays_prior_scale = 10
           )
#m.add_regressor('Christmas')
m.fit(pro_df)
forecast = m.predict(pro_df)
forecast.head(5)

10:19:14 - cmdstanpy - INFO - Chain [1] start processing
10:19:17 - cmdstanpy - INFO - Chain [1] done processing

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2007-07-27,20.908401,15.180277,26.610243,20.908401,20.908401,-0.211933,-0.211933,-0.211933,-0.323598,-0.323598,-0.323598,0.111665,0.111665,0.111665,0.0,0.0,0.0,20.696468
1,2007-07-30,20.888791,15.514808,26.077345,20.888791,20.888791,-0.323418,-0.323418,-0.323418,-0.235942,-0.235942,-0.235942,-0.087476,-0.087476,-0.087476,0.0,0.0,0.0,20.565373
2,2007-07-31,20.882254,15.174048,26.225893,20.882254,20.882254,-0.356357,-0.356357,-0.356357,-0.201858,-0.201858,-0.201858,-0.154499,-0.154499,-0.154499,0.0,0.0,0.0,20.525897
3,2007-08-01,20.875717,15.197758,25.737008,20.875717,20.875717,-0.445552,-0.445552,-0.445552,-0.225367,-0.225367,-0.225367,-0.220185,-0.220185,-0.220185,0.0,0.0,0.0,20.430165
4,2007-08-02,20.869181,14.843972,25.763118,20.869181,20.869181,-0.506676,-0.506676,-0.506676,-0.223071,-0.223071,-0.223071,-0.283605,-0.283605,-0.283605,0.0,0.0,0.0,20.362505

In [6]:
forecast.tail()
with open('../../TrainedModel/fp_tech_indicator/{}.pkl'.format(symbol), 'wb') as f:
     pickle.dump(forecast, f)

In [7]:
forecast["yearly"] = 0
forecast["weekly"] = 0
forecast["ma20above50"] = 0
forecast["ma50above100"] = 0
forecast["ma20above100"] = 0
forecast["ma5"] = 0
forecast["ma10"] = 0
forecast["ma20"] = 0
forecast["ma50"] = 0
forecast["ma100"] = 0
forecast["ema5"] = 0
forecast["ema10"] = 0
forecast["ema20"] = 0
forecast["ema50"] = 0
forecast["ema100"] = 0
forecast["TARGET"] = 0


forecast["Close"] =  pro_df['y'].values

forecast["MA20"] =  pro_df['MA20'].values
forecast["MA100"] =  pro_df['MA100'].values
forecast["MA50"] =  pro_df['MA50'].values
forecast["MA5"] =  pro_df['MA5'].values
forecast["MA10"] =  pro_df['MA10'].values

forecast["EMA20"] =  pro_df['EMA20'].values
forecast["EMA100"] =  pro_df['EMA100'].values
forecast["EMA50"] =  pro_df['EMA50'].values
forecast["EMA5"] =  pro_df['EMA5'].values
forecast["EMA10"] =  pro_df['EMA10'].values
forecast.loc[forecast["Close"].shift(-1) > forecast["Close"],"TARGET"] = 1

forecast.loc[forecast["MA5"] < forecast["Close"],"ma5"] = 1
forecast.loc[forecast["EMA5"] < forecast["Close"],"ema5"] = 1

forecast.loc[forecast["MA10"] < forecast["Close"],"ema10"] = 1
forecast.loc[forecast["EMA10"] < forecast["Close"],"ema10"] = 1


forecast.loc[forecast["MA20"] < forecast["Close"],"ema20"] = 1
forecast.loc[forecast["EMA20"] < forecast["Close"],"ema20"] = 1

forecast.loc[forecast["MA50"] < forecast["Close"],"ema50"] = 1
forecast.loc[forecast["EMA50"] < forecast["Close"],"ema50"] = 1

forecast.loc[forecast["MA100"] < forecast["Close"],"ema100"] = 1
forecast.loc[forecast["EMA100"] < forecast["Close"],"ema100"] = 1




forecast.loc[forecast["yearly"].shift(1) < forecast["yearly"],"yearly"] = 1

forecast.loc[forecast["weekly"].shift(1) < forecast["weekly"],"weekly"] = 1

forecast.loc[forecast["MA20"] > forecast["MA50"],'ma20above50'] = 1
forecast.loc[forecast["MA50"] > forecast["MA100"],'ma50above100'] = 1
forecast.loc[forecast["MA20"] > forecast["MA100"],'ma20above100'] = 1

forecast.dropna(inplace=True)
#new_forecastdf.tail(10)
#forecast['Close'] = pro_df['y'].values
forecast

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,...,MA20,MA100,MA50,MA5,MA10,EMA20,EMA100,EMA50,EMA5,EMA10
0,2007-07-27,20.908401,15.180277,26.610243,20.908401,20.908401,-0.211933,-0.211933,-0.211933,0,...,17.529839,17.613589,18.059852,16.864069,18.059852,17.365265,17.576303,17.680819,16.788946,17.070347
1,2007-07-30,20.888791,15.514808,26.077345,20.888791,20.888791,-0.323418,-0.323418,-0.323418,0,...,17.409935,17.609768,17.971611,16.618573,17.971611,17.241042,17.546296,17.617293,16.546272,16.886815
2,2007-07-31,20.882254,15.174048,26.225893,20.882254,20.882254,-0.356357,-0.356357,-0.356357,0,...,17.307103,17.609057,17.891215,16.485665,17.891215,17.158844,17.523160,17.568692,16.490167,16.794296
3,2007-08-01,20.875717,15.197758,25.737008,20.875717,20.875717,-0.445552,-0.445552,-0.445552,0,...,17.196041,17.606171,17.806551,16.314143,17.806551,17.066860,17.496821,17.514744,16.391119,16.684973
4,2007-08-02,20.869181,14.843972,25.763118,20.869181,20.869181,-0.506676,-0.506676,-0.506676,0,...,17.107841,17.605582,17.738349,16.227163,17.738349,16.982089,17.470681,17.462274,16.319667,16.592571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3947,2023-07-31,86.931737,81.014976,92.227714,86.931737,86.931737,-0.390441,-0.390441,-0.390441,0,...,94.893712,84.175325,90.692617,95.431480,90.692617,94.213245,86.199558,90.645274,95.065405,95.142715
3948,2023-08-01,86.968567,81.079034,91.869610,86.968567,86.968567,-0.422043,-0.422043,-0.422043,0,...,95.005202,84.357118,90.882650,95.033914,90.882650,94.192936,86.354022,90.776832,94.710270,94.934948
3949,2023-08-02,87.005397,81.279819,91.819809,87.005397,87.005397,-0.508972,-0.508972,-0.508972,0,...,95.067986,84.527230,91.033808,94.489999,91.033808,94.160275,86.502457,90.897348,94.423513,94.737685
3950,2023-08-03,87.042227,80.898905,92.011565,87.042227,87.042227,-0.566969,-0.566969,-0.566969,0,...,94.962986,84.694328,91.165362,94.070000,91.165362,94.097392,86.641022,90.999413,94.115675,94.512651
3951,2023-08-04,87.079057,80.838772,91.310904,87.079057,87.079057,-0.723883,-0.723883,-0.723883,0,...,94.768900,84.854273,91.282611,93.480000,91.282611,93.926212,86.753081,91.050416,93.510451,94.110351

In [8]:
new_df = forecast.copy()
#new_df
new_df1 = new_df[["yearly","weekly","ma20above50","ma50above100","ma20above100","ma5","ma20","ma50","ma100","ema5","ema10","ema20","ema50","ema100"]]
new_df1
new_df1.to_csv('data.csv')

In [9]:
c_df = new_df1.iloc[-1]
dd =  c_df.to_dict()
dd

{'yearly': 0,
 'weekly': 0,
 'ma20above50': 1,
 'ma50above100': 1,
 'ma20above100': 1,
 'ma5': 0,
 'ma20': 0,
 'ma50': 0,
 'ma100': 0,
 'ema5': 0,
 'ema10': 1,
 'ema20': 0,
 'ema50': 1,
 'ema100': 1}

In [10]:
new_df.loc[new_df["Close"].shift(-1) > new_df["Close"], "TARGET"] = 1
new_df.loc[new_df["Close"].shift(-1) < new_df["Close"], "TARGET"] = 0
new_df.dropna(inplace=True)

In [11]:
new_df = new_df[["wk","yr","ma20_gr_ma50","TARGET","Range"]]
new_df.to_csv('data.csv')

KeyError: "['wk', 'yr', 'ma20_gr_ma50', 'Range'] not in index"

In [ ]:
#checking missing values in the data
d = new_df.isnull().sum()

In [ ]:
#volum"ma20_gr_ma50","ma50_gr_ma200","ma20_gr_ma200"

lent = new_df.shape[0]
new_d = []
for x in range(0,lent):
    if ( new_df.iloc[x].wk == 1):
       # print(new_df.iloc[x].ma20_gr_ma50)
        new_d.append(new_df.iloc[x].TARGET)
        
r_df = pd.DataFrame({"res":np.array(new_d)})
r_df_f = r_df.loc[r_df["res"] == 0]
print("Full Data: ",lent,"Filterd :",r_df.shape[0],"Ratio :")
r_df.value_counts(normalize=True)
       # new_d.append()
#filterd2 = filterd[filterd["candleUpDay2"]  == 1]

#filterd_tar = filterd[filterd["TARGET"] == 0.0]


#print("Total Length", lent)
#print("Filtered Length : ",filterd.shape[0],filterd_tar.shape[0])
#filterd.TARGET.value_counts(normalize=True)
#filterd.TARGET.value_counts()